demo/apps/blog/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from pypinyin import slug as pinyin_slug
from demo.extensions import db


class Post(db.Model):
    __tablename__ = 'blog_post'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80))
    content = db.Column(db.Text)
    slug = db.Column(db.String(200), unique=True)

    user_id = db.Column(db.Integer, db.ForeignKey('account_user.id'))

    comments = db.relationship('Comment', backref='blog',
                               lazy='dynamic')

    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(),
                           onupdate=db.func.now())

    def __init__(self, title='', content='', user_id='', slug=None):
        self.title = title
        self.content = content
        self.user_id = user_id
        self.slug = slug or pinyin_slug(self.title.replace(' ', ''))

    def __repr__(self):
        return '<Post %r>' % (self.title)


class Comment(db.Model):
    __tablename__ = 'blog_comment'

    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(100))

    user_id = db.Column(db.Integer, db.ForeignKey('account_user.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('blog_post.id'))

    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(),
                           onupdate=db.func.now())

    def __repr__(self):
        return '<Comment %r>' % (self.content[:20])

    def __init__(self, post_id='', user_id='', content=''):
        self.post_id = post_id
        self.user_id = user_id
        self.content = content

demo/apps/blog/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from flask.ext.wtf import Form
from flask.ext.wtf.form import _Auto
from wtforms import TextField, TextAreaField
from wtforms.validators import Required, ValidationError

from .models import Post


class PostForm(Form):
    title = TextField('title', [Required()])
    slug = TextField('slug', [Required()])
    content = TextAreaField('content', [Required()])

    def __init__(self, formdata=_Auto, obj=None, *args, **kwargs):
        self._obj = obj
        super(PostForm, self).__init__(formdata=formdata, obj=obj, *args, **kwargs)

    def validate_slug(form, field):
        slug = field.data
        if form._obj:
            post_id = form._obj.id
            if Post.query.filter(Post.id != post_id, Post.slug == slug).first():
                raise ValidationError('slug exists')
        else:
            if Post.query.filter_by(slug=slug).first():
                raise ValidationError('slug exists')


class CommentForm(Form):
    content = TextAreaField('content', [Required()])

demo/apps/blog/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask import (Blueprint, flash, render_template, redirect,
                   request, url_for, g)
from demo.apps.account.decorators import login_required
from demo.apps.blog.models import Post, Comment
from demo.apps.account.auth import current_user
from demo.extensions import cache, db
from demo.apps.blog.forms import PostForm, CommentForm

blog = Blueprint('blog', __name__, url_prefix='/blog',
                 template_folder='templates')


@cache.memoize(timeout=50)   # cache normal function
def func_foobar(a, b):
    import time
    return a + b + time.time()


@blog.before_request
def before_request():
    if current_user.is_authenticated():
        g.user = current_user
    else:
        g.user = None


@blog.route('/')
@login_required
@cache.cached(timeout=60 * 1, key_prefix='all_posts')  # cache view function
def index():
    # data = Post.query.order_by(db.desc(Post.updated_at)).all()
    data = Post.query.order_by(Post.created_at.desc()).all()
    return render_template('blog/index.html', data=data)


@blog.route('/new/', methods=['GET', 'POST'])
def new():
    form = PostForm()

    if form.validate_on_submit():
        title = form.title.data
        slug = form.title.data
        content = form.content.data

        user_id = g.user.id
        post = Post(title, content, user_id, slug)
        db.session.add(post)
        db.session.commit()

        flash('add success')
        return redirect(url_for('.index'))
    return render_template('blog/add.html', data=None, form=form)


@blog.route('/delete/', methods=['POST'])
def delete():
    post = Post.query.get(request.form['post_id'])
    db.session.delete(post)
    db.session.commit()
    flash('delete success')
    return redirect(url_for('.index'))


@blog.route('/edit/<int:post_id>/<slug>/', methods=['GET', 'POST'])
def edit(post_id, slug):
    post = Post.query.get(post_id)
    form = PostForm(request.form, post)

    if form.validate_on_submit():
        title = form.title.data
        slug = form.slug.data
        content = form.content.data
        user_id = g.user.id

        post.title = title
        post.slug = slug
        post.content = content
        post.user_id = user_id

        db.session.add(post)
        db.session.commit()

        flash('edit success')
        return redirect(url_for('.index'))
    return render_template('blog/add.html', data=post, form=form)


@blog.route('/view/<int:post_id>/<slug>/')
def view(post_id, slug):
    post = Post.query.get_or_404(post_id)
    comments = post.comments
    form = CommentForm()
    return render_template('blog/view.html', post=post, comments=comments,
                           form=form)


@blog.route('/new_comment/<int:post_id>/', methods=['POST'])
@login_required
def new_comment(post_id):
    post = Post.query.get_or_404(post_id)
    form = CommentForm(request.form)
    if form.validate_on_submit():
        comment = Comment(post_id=post.id,
                          user_id=g.user.id,
                          content=form.content.data
                          )
        db.session.add(comment)
        db.session.commit()

    return redirect(request.form['next'])

demo/apps/blog/templates/add.html
{% extends "base.html" %}


{% block content %}
<form action="" method="post">
  <input type="hidden" name="post_id" id="post_id" value="{{ data.id }}" />
  <p>title: <input type="text" name="title" id="title" value="{{ data.title }}" /></p>
  <p>slug: <input type="text" name="slug" id="slug" value="{{ data.slug }}" /></p>
  <p>content: <textarea name="content" id=content rows="8" cols="40">{{ data.content }}</textarea></p>
  <p><input type="submit" value="new post"> </p>
</form>

{% endblock %}

demo/apps/blog/templates/blog/add.html
{% extends "base.html" %}


{% block content %}
<form action="" method="post">
  {{ form.hidden_tag() }}
  <p>{{ form.title.label }} {{ form.title(size=20) }}</p>
  <p>{{ form.slug.label }} {{ form.slug(size=20) }}</p>
  <p>{{ form.content.label }} {{ form.content(size=20) }}</p>

  {% if data %}
  <p><input type="submit" value="update post"> </p>
  {% else %}
  <p><input type="submit" value="new post"> </p>
  {% endif %}
</form>

{% endblock %}

demo/apps/blog/templates/blog/index.html
{% extends "base.html" %}


{% block title %}Blog - {{ super() }}{% endblock %}


{% block content %}

<div> <a href="{{ url_for('blog.new') }}">add</a> </div>

<ul>
  {% for d in data %}
  <li>
    <span><a href="{{ url_for('blog.view', post_id=d.id, slug=d.slug) }}">{{ d.title }}</a></span>
    <span><a href="{{ url_for('blog.edit', post_id=d.id, slug=d.slug) }}">edit</a></span>
    <span>
      <form action="{{ url_for('blog.delete') }}" method="post" style="display: inline">
        <input type="hidden" name="post_id" value="{{ d.id }}" />
        <input type="submit" value="delete" />
      </form>
    </span>
  </li>
  {% endfor %}
</ul>

{% endblock %}

demo/apps/blog/templates/blog/view.html
{% extends "base.html" %}


{% block content %}
<div class="post">
  <h1>{{ post.title }}</h1>
  <p>By {{ post.author.username }}</p>
  <p>{{ post.content }}</p>
</div>

<hr />

<div class="comments">
  {% for comment in comments %}
  <div class="comment" style="border-bottom: 1px solid #aaa">
    <ul>
      <li>author: {{ comment.author }}</li>
      <li>content: {{ comment.content }}</li>
    </ul>
  </div>
  {% endfor %}


  <div class="new_comment">
    <form action="{{ url_for('blog.new_comment', post_id=post.id) }}" method="post">
      {{ form.csrf_token }}
      <p>comment: <textarea name="content" id=content rows="8" cols="40"></textarea></p>
      <input type="hidden" name="next" id="next" value="{{ request.path }}" />
      <input type="submit" name="" id="" value="new comment" />
    </form>
  </div>
</div>

{% endblock %}